version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wallet-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vv90woo4vqu5"
s3_prefix = "wallet-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
